# 중심경향성

   데이터의 중심이 어디 있는 지에 대한 지표가 매우 중요

In [44]:
from scipy import stats
import numpy as np

## 평균

In [3]:
def mean(x) :
    return sum(x)/len(x)

In [4]:
x = [1,2,3,4]

mean(x)

2.5

In [6]:
np.mean(x)

2.5

## 중앙값 구하기

In [17]:
def median(x) :
    x = sorted(x)
    if len(x) % 2 == 0 :
        avr = x[int(len(x)//2 -1)] + x[int(len(x)//2)]
        avr = avr/2
    else :
        avr = x[int(len(x)//2)]
    return avr

In [18]:
median(x)

2.5

In [19]:
y = [1,2,3,4,5]

In [20]:
median(y)

3

In [15]:
np.median(x)

2.5

In [16]:
np.median(y)

3.0

In [21]:
z=[4,3,5,2,1]

In [22]:
median(z)

3

In [23]:
np.median(z)

3.0

## 4분위

In [24]:
def quantile(x,p) :
    p_index = int(p*len(x))
    return sorted(x)[p_index]

In [25]:
quantile(x,0.25)

2

In [31]:
x1 = [1,2,3,4,5,6,7,8,9]

In [32]:
quantile(x1,0.25)

3

In [33]:
quantile(x1,0.5)

5

In [34]:
mean(x1)

5.0

In [35]:
median(x1)

5

### numpy 모듈에서 percentile로 처리

In [36]:
np.percentile(x1, 50)

5.0

## 최빈값

In [37]:
import collections as cols
def mode(x) :
    count = cols.Counter(x)
    max_count = max(count.values())
    return max_count

In [39]:
x2= [1,1,1,2,3,4,5]

In [40]:
mode(x1)

1

### scipy 내의 stats 모듈에서 mode 처리

In [42]:
stats.mode(x2)

ModeResult(mode=array([1]), count=array([3]))

## 데이터의 범위

In [46]:
def data_range(x) :
    return max(x) - min(x)

In [48]:
x

[1, 2, 3, 4]

In [47]:
data_range(x)

3

In [49]:
np.max(x) - np.min(x)

3

# 평균에 얼마나 떨어져 있는 지를 구하기

## 분산

In [51]:
x

[1, 2, 3, 4]

In [52]:
np.var(x)

1.25

In [53]:
def variance(x) :
    return sum([(i-mean(x))**2 for i in x])/len(x)

In [54]:
variance(x)

1.25

## 표준편차

In [55]:
np.std(x)

1.1180339887498949

In [56]:
def standard_d(x) :
    return variance(x)**(1/2)

In [57]:
standard_d(x)

1.118033988749895

# 상관관계

## 공분산 구하기

In [83]:
a = [ 1,2,3,4]
b = [3,4,3,3]

In [84]:
np.cov(a,b)

array([[ 1.66666667, -0.16666667],
       [-0.16666667,  0.25      ]])

In [85]:
def cov(x,y) :
    return sum([ ((i-mean(x))*(j-mean(y))) for i,j in zip(x,y)])/ (len(x)-1)

In [86]:
cov(a,b)

-0.16666666666666666

## 상관계수

In [87]:
def corr_(x,y) :
    return cov(x,y) / (standard_d(x) * standard_d(y) )

In [88]:
corr_(a,b)

-0.3442651863295481

In [89]:
np.cov(a,b)/(np.std(a) * np.std(b))

array([[ 3.44265186, -0.34426519],
       [-0.34426519,  0.51639778]])

In [90]:
np.corrcoef(a,b)

array([[ 1.        , -0.25819889],
       [-0.25819889,  1.        ]])